name: kidguard
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  android_intent_plus: ^6.0.0
  usage_stats: ^1.3.1
  google_sign_in: ^6.3.0
  flutter_launcher_icons: ^0.14.4
  installed_apps: ^2.0.0
  flutter_contacts: ^1.1.9+1
  permission_handler: ^11.3.1
  device_apps: ^2.2.0
  geolocator: ^13.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  workmanager: ^0.6.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  table_calendar: ^3.1.0
  intl: ^0.20.2
  device_info_plus: ^10.1.0
  flutter_gen: ^5.12.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Kid_Guard.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/avatars/boy_1.png
    - assets/avatars/girl_2.png

  fonts:
    - family: CkPuzzleDemo
      fonts:
        - asset: assets/fonts/CkPuzzleDemo.ttf
